name: Run Python Script Weekly

on:
  schedule:
    # This will trigger the action every day at 4 AM UTC
    - cron: '0 4 * * *'  # Runs every day at 4 AM UTC
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (use a requirements.txt file or install directly)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your Provincial script
      - name: Run Provincial script
        run: python _Provincial/ProvExtractor.py

      # Run your Federal script
      - name: Run Federal script
        run: python _Federal/FedExtractor.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data via GitHub Actions"
          git push
  