name: Run Python Script Weekly

on:
  schedule:
    # This will trigger the action every Monday and Wednesday at 4 AM UTC
    - cron: '0 4 * * 1,3'  # Runs on Monday and Wednesday at 4 AM UTC
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (you can use a requirements.txt or install them directly)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your script
      - name: Run Python script
        run: |
          python FedDataExtractor.py
          python ProvDataExtractor.py
