name: Runner

on:
  schedule:
    # This will trigger the action every 8 hours
    - cron: '0 */8 * * *'  # Runs every 8 hours
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Install dependencies (use a requirements.txt file or install directly)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip > /dev/null
          pip install -r requirements.txt > /dev/null
          echo "Dependencies installed"

      # Debug step to print the current working directory
      - name: Print working directory
        run: pwd

      # Run your Provincial script
      - name: Run Provincial script
        run: python _Provincial/ProvExtractor.py

      # Commit and push changes if there are any
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff-index --quiet HEAD --; then
            echo "Processed but no change"
          else
            git add .
            git commit -m "Update data via GitHub Actions"
            git push

