name: Run Python Scripts for Provincial Data

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo history for commits

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run ProvURlLister.py (this script generates the list of URLs)
      - name: Run URL Lister Script
        run: python _Provincial/ProvURlLister.py

      # Run ProvExtractor.py (this script processes the URLs and outputs CSV)
      - name: Run Provincial Script
        run: python _Provincial/ProvExtractor.py

      # Check git status to confirm if there are changes
      - name: Check git status
        run: git status

      # Commit and push changes to GitHub if there are updates
      - name: Check git status and commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git status  # This will show changes if any
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update provincial data" && git push origin main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
