name: Run Python Script Every 8 Hours

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo history for commits

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Provincial data extraction script
      - name: Run Provincial script
        run: python _Provincial/ProvExtractor.py

      # Check git status and see if there are changes
      - name: Check git status
        run: git status

      # Commit and push changes only if there are updates
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add _Provincial/Provincial_district_data.csv
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update data via GitHub Actions" && git push origin main)
