name: Run Python Script Every 8 Hours

on:
  schedule:
    # This will trigger the action every 8 hours
    - cron: '0 */8 * * *'  # Runs every 8 hours
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Install dependencies (use a requirements.txt file or install directly)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Debug step to print the current working directory
      - name: Print working directory
        run: pwd

      # Debug step to list contents of the root directory
      - name: List root directory contents
        run: ls -la

      # Debug step to list contents of the _Provincial directory
      - name: List _Provincial directory contents
        run: ls -la _Provincial

      # Run your Provincial script
      - name: Run Provincial script
        run: python _Provincial/ProvExtractor.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data via GitHub Actions"
          git push
